version: '3'
services: 
  db:
    build: ./db2
    networks:
      - shared
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: DB2INST1_PASSWORD
    ports:
      - "50000:50000"
  flyway:
    build: ./flyway
    networks:
      - shared
networks:
  shared:
    driver: bridge

#docker-compose up --build